### ISSUE TITLE
Downloads 1.007 and then stops

### ISSUE THREAD

**Issue by Justinw1349** [k0rnh0li0/rightclicker#8]
I tried on different devices and each time downloads just 1.007 and then suddenly stops and say something about line 180, but doesn't say error, what can I do to fix that and to download the 10.000?

**Comment by JeevesWantsToKnow** [comment]
Having same issue.

**Comment by Deimuddi** [comment]
much appreciated k0rnh0li0, works like a charm. having the same issue as my frens above now at 929 however. did anyone of y'all figure out what the issue might be?

**Comment by Deimuddi** [comment]
TypeError: 'NoneType' object is not subscriptable
